#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso phaseModel
wclean libso interfacialModels
wclean libso turbulentDispersionModels
wclean libso kineticTheoryModels
wclean libso multiphaseTurbulenceModels
wclean

# ----------------------------------------------------------------- end-of-file
